language: node_js
sudo: false
node_js:
- '0.12'
cache:
  directories:
  - node_modules
  - jspm_packages
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
install:
- npm install
- jspm install
env:
  global:
    secure: FLmNBPw0h4bSDfHjgmSg3HqOuLnDo+GnrQpLxDn12rrWvQtvutxAtkkSdabUpg1ahhjT3SmvziPTOu/XyJ0mozR0qNTKiIAc/YCmH0IiVZU9AiJ4Hy8x8K22ReNVuTwqEgGothdF+VmmTNnYZS4LnP+lRq67G1PW+2stpw7MEvC5yuzhLPOoh/4gEY4D2LvSI8CU37GfUHvaeDgxvQgN7ltrjf0C4lF9CcphTf1wlbAnPh7qzKFqbEcnb61o+smPVBsdv6eEVIoyh1s9YwnH3DNwovZ/L5r4DCkdqhiB06fe3XZnKC7iQ+CFNXTy13q/RxojEyG9SrbRNYjsXqx6fsuU+7ZgHkRj/aa14WLeVhgiv6pz48Y2/XrfNI8YSrgp8CyEylvWx0P72vqqLXwQaZym3Z3zq0Ffx9idSdeAQ/C23R4RBdIDYq4hP62+mRYiKuxl9ejhaMkcf7IjGBE0pxafSQoAXhnSqr644C6X6lx7fW1O76VuA/nPeQd8Wbh9KeJmCXYsCHbAt2QFLFMsksGTKg0Iu75KgclZ+Ndnhbp79orlRP1V7hrtJgl/5nedi5Gqhqe4egml+/N23AsbXimZZSVwh8HXDPv0d0cr+H3qLtZ5/4HwRcU6CIaybc8nALTBnXVTqI9WkkmKMTJzDUC8EN26OKdfRN4DQ0ukxoo=
before_install:
  - npm install -g jspm
  - jspm config registries.github.auth $JSPM_GITHUB_AUTH_TOKEN